### ISSUE TITLE
CHA-10 + Home Assistant + Ebusd

### ISSUE THREAD

**Issue by Naturnobert** [puni2k/ebusd-configuration-wolf#1]
Hi!

I'm in trouble to get your config working. Currently I am running home assistant with John's ebusd.

Almost 1 year ago I did it - somehow. And it worked - somehow. But I had to reinstall everything (backup home assistant). But now it doesn't work anymore.

Any chance to get a bit more instructions how to use it?
Wolf CWL configs (kromschroeder) are working.

Thank you very much in advance,
Naturnorbert

**Comment by Naturnobert** [comment]
Jesus.

"--checkdonfig" solved my problem. 
ebusd stops reading configs if there's a problem with one starting from top to bottom.
CWL configs were checkef befor CHA.

...
I go to sleep. Sorry to disturb you. Thanks for your work. Works flawless!

**Comment by puni2k** [comment]
Don't worry, always willing to lend a hand.

For anybody else interested:

Personally I use the _john30/ebusd_ docker image with the example docker-compose file. All orchestrated with Portainer.
The container gets a volume mounted to _/var/lib/ebusd_ and I have set
`EBUSD_CONFIGPATH: "/var/lib/ebusd/config"`
as well as
`EBUSD_SCANCONFIG: ""`
Under _/var/lib/ebusd/config_ I just have my two config files.
